=== Magnify-Cash/nft-lists/src/tokenlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://nfty.finance/nftlist.schema.json",
  "title": "NFTY Finance NFT List",
  "description": "Schema for lists of NFTs compatible with the NFTY Finance Interface",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when NFTs are removed from the list or NFT addresses are changed.",
          "minimum": 0,
          "examples": [
            1,
            2
          ]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when NFTs are added to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [
            0,
            1
          ]
        }
      },
      "required": [
        "major",
        "minor",
        "patch"
      ]
    },
    "TagIdentifier": {
      "type": "string",
      "description": "The unique identifier of an NFT tag",
      "minLength": 1,
      "maxLength": 10,
      "pattern": "^[\\w]+$",
      "examples": [
        "rare",
        "legendary"
      ]
    },
    "ExtensionIdentifier": {
      "type": "string",
      "description": "The name of an NFT extension property",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[\\w]+$",
      "examples": [
        "color",
        "is_multisig"
      ]
    },
    "ExtensionMap": {
      "type": "object",
      "description": "An object containing any arbitrary or vendor-specific NFT metadata",
      "maxProperties": 10,
      "propertyNames": {
        "$ref": "#/definitions/ExtensionIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/ExtensionValue"
      },
      "examples": [
        {
          "color": "#FF0000",
          "is_verified_by_me": true
        },
        {
          "x-special-properties": {
            "property1": "value1",
            "property2": "value2"
          }
        }
      ]
    },
    "ExtensionPrimitiveValue": {
      "anyOf": [
        {
          "type": "string",
          "minLength": 1,
          "maxLength": 42,
          "examples": [
            "#FF0000"
          ]
        },
        {
          "type": "boolean",
          "examples": [
            true
          ]
        },
        {
          "type": "number",
          "examples": [
            15
          ]
        },
        {
          "type": "null"
        }
      ]
    },
    "ExtensionValue": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner0"
          }
        }
      ]
    },
    "ExtensionValueInner0": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        },
        {
          "type": "object",
          "maxProperties": 10,
          "propertyNames": {
            "$ref": "#/definitions/ExtensionIdentifier"
          },
          "additionalProperties": {
            "$ref": "#/definitions/ExtensionValueInner1"
          }
        }
      ]
    },
    "ExtensionValueInner1": {
      "anyOf": [
        {
          "$ref": "#/definitions/ExtensionPrimitiveValue"
        }
      ]
    },
    "TagDefinition": {
      "type": "object",
      "description": "Definition of an NFT tag that can be associated with an NFT via its identifier",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the NFT tag",
          "pattern": "^[ \\w]+$",
          "minLength": 1,
          "maxLength": 20
        },
        "description": {
          "type": "string",
          "description": "A user-friendly description of the NFT tag",
          "pattern": "^[ \\w\\.,:]+$",
          "minLength": 1,
          "maxLength": 200
        }
      },
      "required": [
        "name",
        "description"
      ],
      "examples": [
        {
          "name": "Rare",
          "description": "An NFT with rare attributes"
        }
      ]
    },
    "NFTInfo": {
      "type": "object",
      "description": "Metadata for a single NFT in an NFT list",
      "additionalProperties": false,
      "properties": {
        "chainId": {
          "type": "integer",
          "description": "The chain ID of the Ethereum network where this NFT is deployed",
          "minimum": 1,
          "examples": [
            1,
            4
          ]
        },
        "address": {
          "type": "string",
          "description": "The checksummed address of the NFT on the specified chain ID",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": [
            "0x0e3a2a1f2146d86a604adc220b4967a898d7fe07"
          ]
        },
        "nftType": {
          "type": "string",
          "description": "The type of NFT (e.g., 'ERC721' or 'ERC1155')",
          "minLength": 1,
          "maxLength": 20,
          "examples": [
            "ERC721",
            "ERC1155"
          ]
        },
        "name": {
          "type": "string",
          "description": "The name of the NFT",
          "minLength": 0,
          "maxLength": 40,
          "anyOf": [
            {
              "const": ""
            },
            {
              "pattern": "^[ \\S+]+$"
            }
          ],
          "examples": [
            "Rare Collectible"
          ]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the NFT",
          "minLength": 0,
          "maxLength": 20,
          "anyOf": [
            {
              "const": ""
            },
            {
              "pattern": "^\\S+$"
            }
          ],
          "examples": [
            "RC"
          ]
        },
        "imageURI": {
          "type": "string",
          "description": "A URI to the NFT image asset; if not set, interface will attempt to find an image based on the NFT address; suggest SVG or PNG of size 256x256",
          "format": "uri",
          "examples": [
            "ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"
          ]
        },
        "tags": {
          "type": "array",
          "description": "An array of tag identifiers associated with the NFT; tags are defined at the list level",
          "items": {
            "$ref": "#/definitions/TagIdentifier"
          },
          "maxItems": 10,
          "examples": [
            "rare",
            "legendary"
          ]
        },
        "extensions": {
          "$ref": "#/definitions/ExtensionMap"
        }
      },
      "required": [
        "chainId",
        "address",
        "nftType",
        "name",
        "symbol"
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the NFT list",
      "minLength": 1,
      "maxLength": 30,
      "pattern": "^[\\w ]+$",
      "examples": [
        "My NFT List"
      ]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "nfts": {
      "type": "array",
      "description": "The list of NFTs included in the list",
      "items": {
        "$ref": "#/definitions/NFTInfo"
      },
      "minItems": 1,
      "maxItems": 10000
    },
    "nftMap": {
      "type": "object",
      "description": "A mapping of key 'chainId_nftAddress' to its corresponding NFT object",
      "minProperties": 1,
      "maxProperties": 10000,
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "$ref": "#/definitions/NFTInfo"
      },
      "examples": [
        {
          "4_0x0e3a2a1f2146d86a604adc220b4967a898d7fe07": {
            "name": "Rare Collectible",
            "address": "0x0e3a2a1f2146d86a604adc220b4967a898d7fe07",
            "symbol": "RC",
            "nftType": "ERC721",
            "chainId": 4,
            "imageURI": "ipfs://QmXttGpZrECX5qCyXbBQiqgQNytVGeZW5Anewvh2jc4psg"
          }
        }
      ]
    },
    "keywords": {
      "type": "array",
      "description": "Keywords associated with the contents of the NFT list; may be used in list discoverability",
      "items": {
        "type": "string",
        "description": "A keyword to describe the contents of the NFT list",
        "minLength": 1,
        "maxLength": 20,
        "pattern": "^[\\w ]+$",
        "examples": [
          "rare",
          "collectible",
          "fantasy"
        ]
      },
      "maxItems": 20,
      "uniqueItems": true
    },
    "tags": {
      "type": "object",
      "description": "A mapping of NFT tag identifiers to their name and description",
      "propertyNames": {
        "$ref": "#/definitions/TagIdentifier"
      },
      "additionalProperties": {
        "$ref": "#/definitions/TagDefinition"
      },
      "maxProperties": 20,
      "examples": [
        {
          "rare": {
            "name": "Rare",
            "description": "An NFT with rare attributes"
          }
        }
      ]
    },
    "logoURI": {
      "type": "string",
      "description": "A URI for the logo of the NFT list; prefer SVG or PNG of size 256x256",
      "format": "uri",
      "examples": [
        "ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"
      ]
    }
  },
  "required": [
    "name",
    "timestamp",
    "version",
    "nfts"
  ]
}

=== Magnify-Cash/nft-lists/test/schema/tokenwithperiodsymbol.nftlist.json
{
  "name": "My NFT List",
  "timestamp": "2023-08-15T12:34:56Z",
  "nfts": [
    {
      "chainId": 1,
      "address": "0x7d8820fa92eb1584636f4f5b8515b5476b75171a",
      "nftType": "ERC721",
      "symbol": "M.F",
      "name": "Murakami.Flowers Official"
    }
  ],
  "version": {
    "major": 1,
    "minor": 0,
    "patch": 0
  }
}
